### ISSUE TITLE
Performance tuning

### ISSUE THREAD

**Issue by alex-nexus** [froveda/ipsy_shopper#6]
I know mongo is fast but for the sake of discussion, what APIs you would do performance tuning?

**Comment by froveda** [comment]
Talking about mongo performance, I think I should use indexes on the most important data so we can get the information faster.

I can also add a cache to get the information without calling the database if it hasn't changed. We can use a module as an intermediary (proxy) between the cache store and the database, and have cache keys using the object *id* plus the *updated at*. This way, if an object hasn't change, then the *updated_at* field won't change either, so if we call the cache with an id and the date, it will fetch the data from the cache. If the updated_at has changed, then it will try to fetch the information with the id and the new updated at date, and since it won't find it, it will query the database and save the new information in the cache

**Comment by alex-nexus** [comment]
how about some specific examples you would do?

**Comment by froveda** [comment]
@alex-nexus currently we don't have a lot of important data to index, but for example, we could index associations to query them faster:

```
belongs_to :album, index: true
has_and_belongs_to_many :playlists, index: true
```

**MongoDB** automatically indexes the `_id` field, so there is no need to create an index for it.

About the cache idea, just as an example, we can this in the song method:

```
class << self
    def find_by_id_cached(id)
    	song = Rails.cache.fetch("song/#{id}") do
    		Song.find(id)
    	end
    
    	song
    end
end

after_save :write_into_cache

private
def write_into_cache
	Rails.cache.write("song/#{self.id}", self)
end
```

This way, when a `Song` is created or updated, it will write the values to the cache. Then, we can find a song doing `Song.find_by_id_cached('someId')` and it will use the cached value or query from the database if it didn't exist.
