### ISSUE TITLE
What if album or playlist GET SHOW APIs need to return songs?

### ISSUE THREAD

**Issue by alex-nexus** [froveda/ipsy_shopper#7]

**Comment by froveda** [comment]
@alex-nexus Currently, *SHOW API* both for *Albums* and *Playlists* returns the songs. Look at the *Body* section here:
- https://ipsy-shopper-api.herokuapp.com/doc/api/v1/albums/retrieving_an_album.html
- https://ipsy-shopper-api.herokuapp.com/doc/api/v1/playlists/retrieving_a_playlist.html

**Comment by alex-nexus** [comment]
I see now. perhaps some performance tuning?

**Comment by alex-nexus** [comment]
I am not sure if I follow how mongo manages its children. Can you show me how an album loads songs to itself?

**Comment by froveda** [comment]
sure @alex-nexus!! could you tell me more information about what do you need me to show you?

**Comment by alex-nexus** [comment]
I saw this line
```
def set_songs
    resource.songs << songs_params[:song_ids].collect { |song_id| Song.find(song_id) }
  end
```
perhaps you can show me how you let mongo store the children(songs) information? Is there another table or there is a list of ids on album or playlist?

**Comment by alex-nexus** [comment]
I got it now. so where do the songs get loaded to the API payload?

**Comment by froveda** [comment]
@alex-nexus Since I'm using `has_and_belongs_to_many`, there is no intermediate table in this case. In a relational database, a table is created but it doesn't have any model since it is not relevant to the application.

You can add songs to a `Playlist` when you [create it](https://ipsy-shopper-api.herokuapp.com/doc/api/v1/playlists/creating_a_playlist.html), [update it](https://ipsy-shopper-api.herokuapp.com/doc/api/v1/playlists/updating_a_playlist.html), or calling the [add_songs](https://ipsy-shopper-api.herokuapp.com/doc/api/v1/playlists/adding_songs.html) api call.

**Comment by alex-nexus** [comment]
I see. I guess I have been asking a dumb question. It seems that the Active Record for Mongo take care of the saving and loading automatically

**Comment by froveda** [comment]
Is a perfect question @alex-nexus!! I have the same doubts when I started working with mongoDB, mainly with mongoid gem
